### ISSUE TITLE
authentication error

### ISSUE THREAD

**Issue by kcoder63** [kcoder63/Edbeepbot#1]
![Screenshot from 2021-02-06 09-10-04](https://user-images.githubusercontent.com/74637789/107108121-b6049b80-685b-11eb-80ea-bc732f2ec8c4.png)
Looks like the problem still exists, two factor authentication is not on
![Screenshot from 2021-02-06 09-11-57](https://user-images.githubusercontent.com/74637789/107108132-cc125c00-685b-11eb-99dd-09fc0a5691dc.png)

**Comment by kcoder63** [comment]
**update**
looks like something's fixed but still not there yet
![Screenshot from 2021-02-06 09-46-16](https://user-images.githubusercontent.com/74637789/107108807-d1be7080-6860-11eb-8c07-628f75e28ad5.png)

**Comment by jai-dewani** [comment]
Oh that must be because you aren't registering access_token and access_token_secret, without them you can't do any action from the account (I think so).  
Twitter docs - [Access Tokens](https://developer.twitter.com/ja/docs/basics/authentication/guides/access-tokens)

**Comment by kcoder63** [comment]
i did with the access token in first one which gave error

**Comment by jai-dewani** [comment]
Think there was some system configuration error, but the project seems to be working in PyCharm. Congrats @kcoder63, should we close this issue then?

**Comment by kcoder63** [comment]
Yep sure! Thanks for helping 😊
