### ISSUE TITLE
[Bug] Screenshot in README

### ISSUE THREAD

**Issue by adityaraute** [kcoder63/Edbeepbot#11]
The profile picture in the Screenshot linked in the README file is different than the current profile picture of the bot on Twitter. 

Please make the necessary changes.

**Comment by kcoder63** [comment]
Thank you, will make the changes 👍

**Comment by kcoder63** [comment]
@all-contributors please add @adityaraute for bug report

**Comment by patel-himanshu** [comment]
@kcoder63, can I take up this issue?

**Comment by kcoder63** [comment]
@patel-himanshu sure you can!

**Comment by kcoder63** [comment]
@patel-himanshu I assigned it to you :)

**Comment by patel-himanshu** [comment]
I have submitted #14 as a pull request. Can't seem to directly link it directly in this discussion. 😅
