### ISSUE TITLE
Retweet all tweets with hashtag 'EddieHub'

### ISSUE THREAD

**Issue by adityaraute** [kcoder63/Edbeepbot#13]
**Is your feature request related to a problem? NO**

**Describe the solution you'd like**
Let the bot retweet all tweets that contain the hashtag #EDDIEHUB

**Additional context**
This will help all followers of the bot get connected and find similar tweets in their timeline.

**Comment by kcoder63** [comment]
that's what it does. It RT #eddiehub and replies to it

**Comment by adityaraute** [comment]
It does? Then add it to the README file or ABOUT section

**Comment by kcoder63** [comment]
It is in the first line of README itself

**Comment by adityaraute** [comment]
Apologies. I guess I woke up blind today.

But this much information in heading makes people wanna skip, so I'd request you to reconsider the markdown.

**Comment by kcoder63** [comment]
Sure! Thank you for suggesting :) Will make the required changes

**Comment by jai-dewani** [comment]
I agree with @adityaraute here, having two H1 headings back to back doesn't helps much

**Comment by kcoder63** [comment]
Yes I'm going to change it

**Comment by jai-dewani** [comment]
Maybe we can add a link to the H2 which says @Edbeepbot on Twitter, to be something like 

## [@Edbeepbot](https://twitter.com/Edbeepbot) on Twitter

and move the `Please do read CONTRIBUTING.md if you want to contribute to this project` like a little down, under the heading `What You Need && Need to Know`, just a suggestion, because we want the person to first know about what eddiebot is and then dive into contributing if needed

**Comment by kcoder63** [comment]
Now? I did add link of twitter account to the twitter icon there but this looks better. Moved the contributing line down

**Comment by jai-dewani** [comment]
Yeah, it looks way better <3   
Any comments @adityaraute from your side?

**Comment by adityaraute** [comment]
I don't see the changes. can u link a PR?

**Comment by jai-dewani** [comment]
The changes are made directly on the `main` branch

**Comment by adityaraute** [comment]
I think that's bad practice. Now reviewers can't even comment on it. Right? I'll create a PR according to the changes I like and then the community can comment on it.

**Comment by kcoder63** [comment]
Sorry will keep that in mind next time 😅 thank you for correcting

**Comment by adityaraute** [comment]
No issue. Please comment on the PR that I have linked and see if it suits the repo's requirements.
